version: "3.9"
services:
  db_car_shop:
    image: postgres
    container_name: db_car_shop
    environment:
      - POSTGRES_PASSWORD=8210
      - POSTGRES_USER=role_arcady
      - POSTGRES_DB=y_lab_car_service
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./db_car_shop/shortcut/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always